-- MySQL Script generated by MySQL Workbench
-- Sun Jan  8 13:54:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nonogram
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nonogram
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nonogram` DEFAULT CHARACTER SET utf8 ;
USE `nonogram` ;

-- -----------------------------------------------------
-- Table `nonogram`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nonogram`.`users` (
  `usersID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `salt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usersID`),
  UNIQUE INDEX `idusers_UNIQUE` (`usersID` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nonogram`.`puzzles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nonogram`.`puzzles` (
  `puzzleID` INT NOT NULL AUTO_INCREMENT,
  `authorID` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `template` LONGTEXT NOT NULL,
  `answer` LONGTEXT NOT NULL,
  `width` INT NOT NULL,
  `height` INT NOT NULL,
  PRIMARY KEY (`puzzleID`, `authorID`),
  UNIQUE INDEX `idpuzzles_UNIQUE` (`puzzleID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nonogram`.`solved_puzzle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nonogram`.`solved_puzzle` (
  `solvedPuzzleID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `puzzleID` INT NOT NULL,
  `time_accessed` VARCHAR(45) NOT NULL,
  `time_left` VARCHAR(45) NOT NULL,
  `solved` TINYINT(1) NOT NULL,
  PRIMARY KEY (`solvedPuzzleID`, `userID`, `puzzleID`),
  UNIQUE INDEX `solved_puzzleID_UNIQUE` (`solvedPuzzleID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nonogram`.`moves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nonogram`.`moves` (
  `movesID` INT NOT NULL AUTO_INCREMENT,
  `solvedPuzzleID` INT NOT NULL,
  `puzzle_state` LONGTEXT NOT NULL,
  PRIMARY KEY (`movesID`, `solvedPuzzleID`),
  UNIQUE INDEX `movesID_UNIQUE` (`movesID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nonogram`.`cookies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nonogram`.`cookies` (
  `cookieID` INT NOT NULL AUTO_INCREMENT,
  `usersID` INT NOT NULL,
  `cookie` VARCHAR(45) NOT NULL,
  `expiration_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cookieID`, `usersID`),
  UNIQUE INDEX `cookieID_UNIQUE` (`cookieID` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
